baseURL = "https://shiftleftcyber.io"
title = "ShiftLeftCyber"
author = "ShiftLeftCyber"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-CR0HB4HF2K"

# Disqus Comment System
#disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logos/ShiftLeftCyberMainLogoUpdated.png"
    alt = "SBOM management solutions by ShiftLeftCyber"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Supply Chain Security"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "ShiftLeftCyber helps manage Software Bill of Materials (SBOM) with compliance-focused solutions, enhancing cyber resilience."
    meta_og_title = "ShiftLeftCyber"
    meta_og_type = "website"
    meta_og_url = "https://shiftleftcyber.io"
    meta_og_image = "https://shiftleftcyber.io/img/high-res/metaimage.jpg"
    meta_og_description = "Discover our innovative solutions and read our latest insights on our blog."
    meta_og_author = "ShiftLeftCyber"
    meta_og_keywords = "SBOM, Software Bill of Materials, compliance, security, audit-ready reporting, cyber resilience, CycloneDX, SPDX"

[menu]

  [[menu.main]]
    identifier = "securesbom"
    name = "SBOM Signing FAQ"
    url = "/faq/"
    weight = 1

  [[menu.main]]
    identifier = "securesbom_vs_sigstore"
    name = "SecureSBOM vs Sigstore"
    url = "/securesbom_vs_sigstore/"
    weight = 2

  # ToDo - Add this back in when we have a better grasp of our professional services
  #[[menu.main]]
  #  identifier = "products"
  #  name = "Products & Services"
  #  url = "/products/"
  #  weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contactus/"
    weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/shiftleftcyber/"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
